In [1]:
# pip install pandas
# pip install matplotlib
# pip install psycopg2
# pip install seaborn
# pip install sqlalchemy
# pip install scikit-learn

In [2]:
import pandas as pd
from sqlalchemy import create_engine

## Create Database Connection

In [3]:
engine =create_engine("postgresql://postgres:postgres4354@localhost:5432/banking_fraud")

## Load Fraud Dataset from SQL

In [4]:
query = "SELECT * FROM fraud_dataset"
df = pd.read_sql(query, engine)

In [5]:
df.head()

,transaction_id,customer_id,full_name,age,gender,customer_city,account_type,transaction_date,transaction_type,amount,merchant_category,transaction_location,device_type,is_fraud
0,1,3026,Sanjay Nair,57,Female,Chennai,Current,2024-04-28 19:28:00,POS Payment,6837.38,Electronics,Pune,POS,0
1,2,3010,Ritu Mehta,49,Male,Chennai,Current,2023-11-03 05:06:00,Online Payment,7136.13,Electronics,Lucknow,POS,0
2,3,3719,Sneha Singh,56,Female,Hyderabad,Current,2024-03-02 04:53:00,ATM Withdrawal,8149.16,Travel,Bangalore,Web,0
3,4,575,Ritu Mehta,34,Male,Pune,Savings,2024-02-21 14:11:00,POS Payment,15869.78,Utilities,Delhi,ATM,0
4,5,3649,Karan Patel,64,Male,Chennai,Savings,2023-01-04 07:10:00,Online Payment,3982.19,Shopping,Bangalore,ATM,0

In [6]:
df.shape

(100000, 14)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 14 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   transaction_id        100000 non-null  int64
 1   customer_id           100000 non-null  int64
 2   full_name             100000 non-null  object
 3   age                   100000 non-null  int64
 4   gender                100000 non-null  object
 5   customer_city         100000 non-null  object
 6   account_type          100000 non-null  object
 7   transaction_date      100000 non-null  datetime64[ns]
 8   transaction_type      100000 non-null  object
 9   amount                100000 non-null  float64
 10  merchant_category     100000 non-null  object
 11  transaction_location  100000 non-null  object
 12  device_type           100000 non-null  object
 13  is_fraud              100000 non-null  int64
dtypes: datetime64[ns](1), float64(1), int64(4), object(8)
memory usage: 10.7+ MB

In [8]:
df.describe()

,transaction_id,customer_id,age,transaction_date,amount,is_fraud
count,100000.000000,100000.000000,100000.000000,100000,100000.000000,100000.000000
mean,50000.500000,2505.255290,43.060920,2023-12-16 07:17:58.360200192,11647.251688,0.041000
min,1.000000,1.000000,21.000000,2023-01-01 00:06:00,50.090000,0.000000
25%,25000.750000,1261.000000,32.000000,2023-06-23 17:04:15,5216.505000,0.000000
50%,50000.500000,2538.000000,43.000000,2023-12-16 21:16:30,10379.560000,0.000000
75%,75000.250000,3728.000000,54.000000,2024-06-08 00:43:00,15553.910000,0.000000
max,100000.000000,5000.000000,65.000000,2024-11-30 23:57:00,89978.230000,1.000000
std,28867.657797,1443.830375,12.949969,NaN,10898.672931,0.198291

In [9]:
df.columns

Index(['transaction_id', 'customer_id', 'full_name', 'age', 'gender',
       'customer_city', 'account_type', 'transaction_date', 'transaction_type',
       'amount', 'merchant_category', 'transaction_location', 'device_type',
       'is_fraud'],
      dtype='object')

In [10]:
df['is_fraud'].value_counts()

is_fraud
0    95900
1     4100
Name: count, dtype: int64

In [11]:
df['is_fraud'].value_counts(normalize=True)*100.0 #fraud_percentage

is_fraud
0    95.9
1     4.1
Name: proportion, dtype: float64

## Fraud Analysis by Transaction Amount

In [12]:
df.groupby('is_fraud')['amount'].mean() #average amount for fraud vs normal transactions.

is_fraud
0     9984.553236
1    50538.174017
Name: amount, dtype: float64

In [13]:
df.groupby('is_fraud')['amount'].describe()

,count,mean,std,min,25%,50%,75%,max
is_fraud,,,,,,,,
0,95900.0,9984.553236,5754.933970,50.09,4998.4625,9954.390,14957.47,19999.93
1,4100.0,50538.174017,23353.287392,10032.22,30064.5625,50059.895,71271.17,89978.23

## Fraud by Device Type

In [14]:
df.groupby('device_type')['is_fraud'].sum().sort_values(ascending=True)
# This shows how many frauds occurred on each device.

device_type
POS        997
Web       1016
ATM       1030
Mobile    1057
Name: is_fraud, dtype: int64

## fraud rate by device

In [15]:
# fraud_rate = df['is_fraud'].sum()*100.0/df['transaction_id'].count()
# df.groupby('device_type')['is_fraud'].sum()*100.0/df['transaction_id'].count()
device_type=df.groupby('device_type')['is_fraud'].agg(['sum','count'])
device_type['fraud_rate']=(device_type['sum']/device_type['count'])*100.0
device_type.sort_values('fraud_rate',ascending=False)

              sum  count  fraud_rate
device_type
Mobile       1057  25076    4.215186
ATM          1030  24938    4.130243
Web          1016  24877    4.084094
POS           997  25109    3.970688

## Encode Categorical Variables

### one hot encoding

In [16]:
df_encoded = pd.get_dummies(df,drop_first=True) #convert categorical columns into numbers
df_encoded.shape

(100000, 189)

In [17]:
df_encoded['transaction_date']

0       2024-04-28 19:28:00
1       2023-11-03 05:06:00
2       2024-03-02 04:53:00
3       2024-02-21 14:11:00
4       2023-01-04 07:10:00
                ...
99995   2023-07-23 09:56:00
99996   2024-08-31 11:04:00
99997   2024-08-22 18:10:00
99998   2023-10-20 09:03:00
99999   2023-05-08 14:34:00
Name: transaction_date, Length: 100000, dtype: datetime64[ns]

In [18]:
df_encoded['year'] = df_encoded['transaction_date'].dt.year
df_encoded['month'] = df_encoded['transaction_date'].dt.month
df_encoded['day'] = df_encoded['transaction_date'].dt.day
df_encoded['hour'] = df_encoded['transaction_date'].dt.hour

df_encoded = df_encoded.drop('transaction_date', axis=1)

In [19]:
df_encoded[['year','month','day','hour']].head()

   year  month  day  hour
0  2024      4   28    19
1  2023     11    3     5
2  2024      3    2     4
3  2024      2   21    14
4  2023      1    4     7

# Build the Fraud Detection Model

## Split Features and Target

In [20]:
X = df_encoded.drop('is_fraud', axis=1) #input features
y = df_encoded['is_fraud']#target variable

## Train/Test Split

In [21]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
   X, y, test_size=0.2, random_state=42
)

## Train Logistic Regression

In [22]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [23]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=2000)

model.fit(X_train_scaled, y_train)

LogisticRegression(max_iter=2000)

## Model Prediction

In [24]:
y_pred = model.predict(X_test_scaled)

## Evaluate Model Performance

In [25]:
from sklearn.metrics import accuracy_score, confusion_matrix

print("Accuracy:", accuracy_score(y_test, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.99275
Confusion Matrix:
[[19191     0]
 [  145   664]]

In [26]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      1.00     19191
           1       1.00      0.82      0.90       809

    accuracy                           0.99     20000
   macro avg       1.00      0.91      0.95     20000
weighted avg       0.99      0.99      0.99     20000

# Better Fraud Model (Random Forest)

In [27]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)
rf_model.fit(X_train, y_train)
rf_pred = rf_model.predict(X_test)

In [28]:
print(classification_report(y_test, rf_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     19191
           1       1.00      0.89      0.94       809

    accuracy                           1.00     20000
   macro avg       1.00      0.94      0.97     20000
weighted avg       1.00      1.00      1.00     20000

## Feature Importance

In [29]:
import pandas as pd

feature_importance = pd.Series(
    rf_model.feature_importances_,
    index=X_train.columns
).sort_values(ascending=False)

feature_importance.head(10)

amount                  0.764902
transaction_id          0.023131
customer_id             0.017285
day                     0.017020
hour                    0.016255
month                   0.014140
age                     0.013588
year                    0.004793
account_type_Savings    0.004544
device_type_Web         0.003664
dtype: float64

# Export Dataset from Python

In [32]:
df.to_csv("Banking_fraud_detection.csv",index=False)